### ISSUE TITLE
Suggestion - use spans instead of strongs

### ISSUE THREAD

**Issue by jzhu01** [JanSonMuc/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/JanSonMuc/prj-rev-bwfs-dasmoto/blob/master/Desmoto/index.html#L13

Since the strong tag is a stylistic one, we're essentially doing CSS work outside of the CSS. Instead, I suggest using spans, and then giving the spans a class and styling it in the CSS. This way, we keep our stylings in the CSS and our content/structure in the HTML.

**Comment by JanSonMuc** [comment]
Thanx! Good advice :)
